Well this pull request is not working, I pushed it because it does illustrate a a Py 3 bug in one of the cromlech libraries, cromlech.zodb so I thought I would push it out to the server for you to take a look at if the detailed error report is not enough.  I think we saw the same bug earlier in the dolmen.container.
 Here is the core problem, the full backtrace follows

 File "/home/lozinski/code/cromlech/CromlechCromDemo/eggs/cromlech.zodb-0.3.1-\
py3.4.egg/cromlech/zodb/components.py", line 20, in PossibleSite
    zope.interface.implements(zope.component.interfaces.IPossibleSite)
  File "/home/lozinski/code/cromlech/CromlechCromDemo/eggs/zope.interface-4.4.3\
-py3.4-linux-x86_64.egg/zope/interface/declarations.py", line 483, in implement\
s
    raise TypeError(_ADVICE_ERROR % 'implementer')
TypeError: Class advice impossible in Python3.  Use the @implementer class deco\
rator instead.

AND HERE THE FULL BACKTRACE FOLLOWS

!uw
uwsgi --http :8081 --wsgi-file server.py
*** Starting uWSGI 2.0.15 (64bit) on [Thu Dec 14 13:19:15 2017] ***
compiled with version: 4.9.2 on 04 December 2017 19:15:18
os: Linux-4.9.50-x86_64-linode86 #1 SMP Thu Sep 14 19:28:20 UTC 2017
nodename: pythonlinks.info
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 2
current working directory: /home/lozinski/code/cromlech/CromlechCromDemo
detected binary path: /home/lozinski/code/cromlech/venv3/bin/uwsgi
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 15779
your memory page size is 4096 bytes
detected max file descriptor number: 65536
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on :8081 fd 4
spawned uWSGI http 1 (pid: 1838)
uwsgi socket 0 bound to TCP address 127.0.0.1:45051 (port auto-assigned) fd 3
Python version: 3.4.2 (default, Oct  8 2014, 10:47:48)  [GCC 4.9.1]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x137eb00
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 72768 bytes (71 KB) for 1 cores
*** Operational MODE: single process ***
Traceback (most recent call last):
  File "server.py", line 47, in <module>
    from cromlech.zodb import init_db_from_file
  File "/home/lozinski/code/cromlech/CromlechCromDemo/eggs/cromlech.zodb-0.3.1-py3.4.egg/cromlech/zodb/__init__.py", line 4, in <module>
    from .components import PossibleSite, LocalSiteManager
  File "/home/lozinski/code/cromlech/CromlechCromDemo/eggs/cromlech.zodb-0.3.1-py3.4.egg/cromlech/zodb/components.py", line 16, in <module>
    class PossibleSite(object):
  File "/home/lozinski/code/cromlech/CromlechCromDemo/eggs/cromlech.zodb-0.3.1-py3.4.egg/cromlech/zodb/components.py", line 20, in PossibleSite
    zope.interface.implements(zope.component.interfaces.IPossibleSite)
  File "/home/lozinski/code/cromlech/CromlechCromDemo/eggs/zope.interface-4.4.3-py3.4-linux-x86_64.egg/zope/interface/declarations.py", line 483, in implements
    raise TypeError(_ADVICE_ERROR % 'implementer')
TypeError: Class advice impossible in Python3.  Use the @implementer class decorator instead.
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 1837, cores: 1)
lozinski@pythonlinks:~/code/cromlech/CromlechCromDemo$